import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";
import { FamilyProvider } from "@/context/FamilyContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PanelLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={`h-full`}>
        <FamilyProvider>{children}</FamilyProvider>
      </body>
    </html>
  );
}
